[project]
name = "handoff-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agents",
    "dotenv>=0.9.9",
    "openai>=1.95.1",
    "openai-agents>=0.1.0",
    "pyttsx3>=2.99",
    "speechrecognition>=3.14.3",
]
